logging.level:
  root: INFO
  org.springframework.jdbc.core: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
  org.springframework.jdbc.core.JdbcTemplate: DEBUG
  pe.cmacica.labs.labs03: DEBUG


server.port: 8085

#Conexi√≥n bd
spring.datasource.url: jdbc:mysql://localhost:3308/customersdb?useSSL=false
spring.datasource.username: user
spring.datasource.password: password
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect


#Inicializar bd
spring.jpa.hibernate.ddl-auto: create-drop
spring.datasource.initialization-mode: always
